# Generated by Django 3.0.8 on 2020-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200815_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='Tell the readers a bit about YOU', max_length=500),
        ),
    ]
